version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: test-mysql-container
    networks:
      - my-network
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0224
      MYSQL_DATABASE: dev_database
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-container
    networks:
      - my-network
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3310
      MYSQL_USER: root
      MYSQL_PASSWORD: 0224
      MYSQL_DATABASE: dev_database
    command: ["sh", "-c", "npx prisma db push && npm start"]

networks:
  my-network:
    driver: bridge
